package BlackMarket;

import java.sql.*;
import javax.swing.*;
import javax.swing.JFileChooser;
import net.proteanit.sql.DbUtils;
import java.awt.event.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;

public class Employee_info extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    //Creates new form Employee_info
    public Employee_info() {
        initComponents();
        conn = javaconnect.ConnecrDb();
        Update_table();
    }
 //Update Table
 private void Update_table(){
    try{
        String sql = "select EmployeeID, fName, lName, SecurityLevel, Country, UserName from Employee";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        table_employee.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e ){
        JOptionPane.showMessageDialog(null,e);    
    } finally {
    try{
        rs.close();
        pst.close();
        //conn.close();    
    } catch (Exception e){
        JOptionPane.showMessageDialog (null, e);
    }    
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_employee = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_employeeid = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        fire = new javax.swing.JButton();
        txt_security = new javax.swing.JTextField();
        txt_country = new javax.swing.JTextField();
        attach_image = new javax.swing.JButton();
        txt_attach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Security Level", "Country"
            }
        ));
        table_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_employeeMouseClicked(evt);
            }
        });
        table_employee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_employeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_employeeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_employee);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Employee ID");

        jLabel4.setText("Security Level");

        jLabel5.setText("Country");

        save.setText("ADD");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setText("UPDATE");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        fire.setText("FIRE");
        fire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireActionPerformed(evt);
            }
        });

        txt_security.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_securityActionPerformed(evt);
            }
        });

        attach_image.setText("Attach Image");
        attach_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_imageActionPerformed(evt);
            }
        });

        jLabel7.setText("EMPLOYEE INFO");

        jButton1.setText("View Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("User Name");

        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });

        jButton3.setText("Manage Items");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fire))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addComponent(attach_image))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_fname)
                                    .addComponent(txt_lname)
                                    .addComponent(txt_employeeid)
                                    .addComponent(txt_security)
                                    .addComponent(txt_country)
                                    .addComponent(txt_attach, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(user_name))))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(52, 52, 52)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel7)
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_security, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(txt_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_attach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(attach_image))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(save)
                                .addComponent(edit)
                                .addComponent(fire)))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_employeeMouseClicked
        // TODO add your handling code here:
         int row = table_employee.getSelectedRow();
         String Table_click =(table_employee.getModel().getValueAt(row, 0).toString()); 
         
         //Get image from Employee DB
         try{
             String sql = "select Image from Employee where EmployeeID ='"+Table_click+"'";  
             pst = conn.prepareStatement(sql);
              rs = pst.executeQuery();
            
            if(rs.next()){
                byte[]imagedata = rs.getBytes("Image");
                format = new ImageIcon(imagedata);
                image.setIcon(format);
            }
        }catch(Exception e){
            e.printStackTrace();   
        }finally {
        try{
            rs.close();
            pst.close();
            //conn.close();
       } catch (Exception e){
           JOptionPane.showMessageDialog (null, e);
        }     
    }
        //Pull info and display  
        try{     
         String sql = "select * from Employee where EmployeeID='"+Table_click+"' ";
         pst = conn.prepareStatement(sql);
         rs = pst.executeQuery();
         if(rs.next()){
             
             String add1 = rs.getString("EmployeeID");
             txt_employeeid.setText(add1);
             
             String add2 = rs.getString("fName");
             txt_fname.setText(add2);
             
             String add3 = rs.getString("lName");
             txt_lname.setText(add3);
             
             String add4 = rs.getString("SecurityLevel");
             txt_security.setText(add4);
             
             String add5 = rs.getString("Country");
             txt_country.setText(add5);   
             
             String add6 = rs.getString("UserName");
             user_name.setText(add6); 
         }   
         }catch(Exception e){    
           JOptionPane.showMessageDialog(null,e);            
        }finally {
       try{
            rs.close();
            pst.close();
             //conn.close();
    } catch (Exception e){
            JOptionPane.showMessageDialog (null, e);
    }    
    }
    }//GEN-LAST:event_table_employeeMouseClicked

    private void txt_securityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_securityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_securityActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // save new employees 
        try{    
            String sql ="Insert into Employee (EmployeeID,fName,lName,SecurityLevel,Country, Image, UserName) values(?,?,?,?,?,?,?) ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_employeeid.getText());
            pst.setString(2, txt_fname.getText());
            pst.setString(3, txt_lname.getText());
            pst.setString(4, txt_security.getText());
            pst.setString(5, txt_country.getText());
            pst.setBytes(6, person_image);    
            pst.setString(7, user_name.getText());
            pst.execute();
            
            txt_employeeid.setText("");
            txt_fname.setText("");
            txt_lname.setText("");
            txt_security.setText("");
            txt_country.setText("");
            txt_attach.setText("");
            user_name.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally {
       try{
            rs.close();
            pst.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog (null, e);
        }    
    }
        Update_table();
    }//GEN-LAST:event_saveActionPerformed

    private void fireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireActionPerformed
        // Delete employee
        int p = JOptionPane.showConfirmDialog(null,"Do you want to Fire Employee","Terminate Agent",JOptionPane.YES_NO_OPTION );
        if(p==0){
        String sql = "delete from Employee where fName=?";
            try{        
               pst = conn.prepareStatement(sql);        
               pst.setString(1, txt_fname.getText());        
               pst.execute();
               JOptionPane.showMessageDialog(null, "Deleted");   
               
               txt_employeeid.setText("");
               txt_fname.setText("");
               txt_lname.setText("");
               txt_security.setText("");
               txt_country.setText("");
               user_name.setText("");
               
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally {
   try{
        rs.close();
        pst.close();
    } catch (Exception e){
        JOptionPane.showMessageDialog (null, e);
    }   
    }
        Update_table();
        }
    }//GEN-LAST:event_fireActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // edit employee list
        try{
            String value1 = txt_fname.getText();
            String value2 = txt_lname.getText();
            String value3 = txt_employeeid.getText();
            String value4 = txt_security.getText();
            String value5 = txt_country.getText();
            String value6 = user_name.getText();
            String sql = "update Employee set employeeID='"+value3+"' ,fName = '"+value1+"',lName='"+value2+"',SecurityLevel='"+value4+"',Country='"+value5+"', UserName='"+value6+"' where EmployeeID='"+value3+"'" ;
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally {
        try{
            rs.close();
            pst.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog (null, e);
    }    
    }
        Update_table();
    }//GEN-LAST:event_editActionPerformed

    private void table_employeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_employeeKeyPressed
        // arrows displays information
        
    }//GEN-LAST:event_table_employeeKeyPressed

    private void table_employeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_employeeKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_UP){
            
            try{
         int row = table_employee.getSelectedRow();
         String Table_click =(table_employee.getModel().getValueAt(row, 0).toString()); 
          
         String sql = "select * from Employee where EmployeeID='"+Table_click+"' ";
         pst = conn.prepareStatement(sql);
         rs = pst.executeQuery();
         if(rs.next()){
             
             String add1 = rs.getString("EmployeeID");
             txt_employeeid.setText(add1);
             
             String add2 = rs.getString("fName");
             txt_fname.setText(add2);
             
             String add3 = rs.getString("lName");
             txt_lname.setText(add3);
             
             String add4 = rs.getString("SecurityLevel");
             txt_security.setText(add4);
             
             String add5 = rs.getString("Country");
             txt_country.setText(add5);             
           
             
         }   
        }catch(Exception e){
            
       JOptionPane.showMessageDialog(null,e);    
            
        } finally {
        
   try{
        rs.close();
        pst.close();
        //conn.close();
        
    } catch (Exception e){
    }        
    }         
        }
        
    }//GEN-LAST:event_table_employeeKeyReleased

    private void attach_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attach_imageActionPerformed
        // Attach photo from file
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        txt_attach.setText(filename);
        
        try{
            File image= new File (filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum= fis.read(buf))!=-1;){    
            bos.write(buf,0,readNum);
            }
           person_image=bos.toByteArray(); 
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null,e);   
        }
    }//GEN-LAST:event_attach_imageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        viewCustomer regFace = new viewCustomer();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login regFace = new Login();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        insertItem regFace = new insertItem();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_info().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attach_image;
    private javax.swing.JButton edit;
    private javax.swing.JButton fire;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    private javax.swing.JTable table_employee;
    private javax.swing.JTextField txt_attach;
    private javax.swing.JTextField txt_country;
    private javax.swing.JTextField txt_employeeid;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_security;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables

private ImageIcon format = null;
String filename=null;
int s=0;
byte[] person_image=null;
}
